### ISSUE TITLE
In neomutt, add binding to jump to next mailbox with unread messages

### ISSUE THREAD

**Issue by jladdjr** [jladdjr/bootstrap#8]
Having to hit down until I hit a mailbox with new messages takes a while and I find myself doing it all. the. time.

https://neomutt.org/guide/advancedusage.html#13-2-%C2%A0polling-for-new-mail mentions a function for this - `<next-unread-mailbox>`

**Comment by jladd-test** [comment]
@jladdjr test

**Comment by jladd-test** [comment]
@jladdjr 

Cupcake ipsum dolor sit amet sweet roll danish. Sugar plum tootsie roll lollipop sugar plum chocolate cake pie wafer jujubes jujubes. Brownie pudding jelly sesame snaps halvah brownie pastry cotton candy. Cookie cotton candy apple pie. Bear claw powder lollipop macaroon pie wafer gummi bears wafer toffee. Oat cake halvah caramels. Jelly beans muffin candy candy. Gummies bonbon pie chocolate cake muffin chupa chups. Chocolate bar icing brownie liquorice. Pie powder liquorice dragée cake cake toffee cupcake croissant. Tart apple pie pudding. Gummies pudding jelly chupa chups croissant. Marshmallow macaroon sweet roll sesame snaps.

Carrot cake jujubes halvah. Croissant chocolate gummi bears marzipan toffee carrot cake. Cookie marzipan marshmallow jelly chocolate pie bonbon icing. Dragée toffee apple pie halvah sweet roll bonbon gummi bears. Topping biscuit cotton candy. Pudding cake sweet. Cotton candy gummies powder chocolate cake halvah gummi bears pudding cotton candy marshmallow. Lemon drops liquorice donut sweet. Cupcake cake topping. Muffin chocolate tiramisu. Macaroon dessert lemon drops. Muffin marzipan candy biscuit sweet roll. Chupa chups halvah donut pastry.

Brownie icing sugar plum. Cupcake lollipop cheesecake pudding. Jelly lollipop ice cream. Lemon drops jujubes cupcake jujubes. Cake jelly oat cake chocolate. Icing gingerbread biscuit sugar plum. Tootsie roll gummi bears chocolate sesame snaps dragée dragée toffee. Apple pie marshmallow muffin. Gummi bears sweet roll gingerbread chocolate cheesecake oat cake pie cake. Tart cookie sesame snaps jujubes cookie liquorice tiramisu dragée. Candy canes cake cotton candy fruitcake cupcake cake. Cupcake cake sweet gingerbread icing jujubes. Tiramisu caramels chocolate bar jelly-o pie wafer marshmallow. Apple pie gummi bears halvah pie apple pie oat cake.

Sesame snaps lollipop cake pastry tiramisu. Caramels soufflé gummi bears macaroon jelly chocolate gingerbread gingerbread marzipan. Brownie jelly pie bear claw pie jelly beans tootsie roll liquorice cupcake. Marshmallow jelly-o carrot cake gingerbread gummies macaroon. Cotton candy sweet roll topping jujubes oat cake oat cake chocolate cake fruitcake. Sugar plum gummies tootsie roll tootsie roll chocolate cake cake. Lollipop donut dessert liquorice sweet jujubes icing toffee dessert. Caramels toffee sesame snaps bear claw carrot cake dragée. Jujubes gummi bears cheesecake sesame snaps donut. Candy canes sugar plum cotton candy brownie. Cupcake cotton candy lollipop biscuit. Sugar plum cookie sweet roll caramels biscuit danish. Tiramisu jelly beans cupcake halvah cake jelly. Biscuit cake caramels.

Pie chocolate marzipan candy liquorice sweet roll. Icing tootsie roll pie gingerbread jelly beans. Liquorice brownie cake jelly-o powder liquorice pastry. Liquorice tart dragée tiramisu pie pie macaroon marshmallow. Candy canes cheesecake dragée toffee lollipop. Brownie jelly beans pudding brownie gummi bears. Muffin apple pie tart chupa chups halvah liquorice. Croissant chocolate bar dessert. Soufflé gingerbread sweet carrot cake gingerbread. Caramels cake gummi bears chocolate cake cheesecake. Tart fruitcake ice cream powder wafer tootsie roll liquorice. Cheesecake gummies apple pie powder marshmallow jujubes. Muffin bear claw sugar plum dessert candy canes cake jelly beans macaroon powder.
